---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Lenguaje de Modelo Único
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Lenguaje de Modelado Unificado
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Lenguaje de Mapas sobre Uniones
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: UML
