---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Herencia Multinivel
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Herencia Jerárquica
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Herencia Simple
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Herencia Múltiple
  checked: false
name: Nuevo ejercicio
