---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@Qualifier"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@AutoWired"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@Service"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@Entity"
  checked: true
name: Anotaciones
