---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LinkedList
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Collection
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Iterator
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Comparator
  checked: true
name: Nuevo ejercicio
