---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Exception
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Error
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Throwable
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: Excepciones y errores
