---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Asociación
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Agregación
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Composición
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: Relaciones
