---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LIKE "Juan%"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LIKE "Juan*"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LIKE "Juan$"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: LIKE "Juan&"
  checked: false
name: Nuevo ejercicio
