---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No se puede repetir en dos elementos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Es reutilizable
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Debe ir siempre
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna es cierta
  checked: false
name: CSS
