---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Atributos de objeto
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Atributos de clase estáticos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Variables finales
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: Nuevo ejercicio
