---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: EntityManager
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: PersistenceUnit
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: EntityManagerFactory
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Entity
  checked: false
name: JPA
