---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@OneToOne"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@ManyToMany"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@ManyToOne"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "@OneToMany"
  checked: false
name: Tipos de relación
