---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: OK, petición procesada correctamente.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Indica al browser que visite otra dirección.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Acceso prohibido, por falta de permisos.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No encontrado, cuando el documento no existe.
  checked: false
name: HTTP
