---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: XML
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: UML
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: MVC
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: EVC
  checked: false
name: Arquitectura
